### ISSUE TITLE
make test error: test/catch.hpp:6631:45: size of array ‘altStackMem’ is not an integral constant-expression

### ISSUE THREAD

**Issue by lufuhao** [gatech-genemark/spaln-boundary-scorer#3]
Hi, I met a error when 'make test' on ubuntu 22.01. Would you please help with this?

G++: 11.3.0
kernal: 5.19.0-43-generic
MachType: x86_64

Brief description:
make .... OK
make test .... Error

---make log------
g++ -c -Wall -std=c++0x Alignment.cpp -o Alignment.o
g++ -MM -c -Wall -std=c++0x Alignment.cpp > Alignment.d
g++ -c -Wall -std=c++0x Parser.cpp -o Parser.o
g++ -MM -c -Wall -std=c++0x Parser.cpp > Parser.d
g++ -c -Wall -std=c++0x ScoreMatrix.cpp -o ScoreMatrix.o
g++ -MM -c -Wall -std=c++0x ScoreMatrix.cpp > ScoreMatrix.d
g++ -c -Wall -std=c++0x Kernel.cpp -o Kernel.o
g++ -MM -c -Wall -std=c++0x Kernel.cpp > Kernel.d
g++ -c -Wall -std=c++0x main.cpp -o main.o
g++ -MM -c -Wall -std=c++0x main.cpp > main.d
g++  Alignment.o Parser.o ScoreMatrix.o Kernel.o main.o -o spaln_boundary_scorer

------make test log -----------
g++ -c -Wall -std=c++0x test/t_parser.cpp -o test/t_parser.o
g++ -MM -c -Wall -std=c++0x test/t_parser.cpp > test/t_parser.d
g++ -c -Wall -std=c++0x test/tests.cpp -o test/tests.o
In file included from /usr/include/signal.h:328,
                 from test/catch.hpp:6456,
                 from test/tests.cpp:3:
test/catch.hpp:6631:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 6631 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                             ^~~~~~~~
make: *** [Makefile:33: test/tests.o] Error 1

**Comment by tomasbruna** [comment]
This only affects the build of unit tests, so you don't have to worry about it. The main binary itself seems fine. If you want to build the tests, you'll need to update the Catch framework.

**Comment by lufuhao** [comment]
Thank you so much for your reply. this really helps.

发自我的 iPhone

在 2023年7月6日，22:57，Tomáš Brůna ***@***.***> 写道：

﻿

This only affects the build of unit tests, so you don't have to worry about it. The main binary itself seems fine. If you want to build the tests, you'll need to update the Catch framework.
